---
- name: install check_mk-agent
  action: yum name=check_mk-agent state=latest

- name: copy host.mk template
  action: template src=host.mk.j2 dest=/etc/check_mk/conf.d/{{ansible_hostname}}.mk mode=0644
  delegate_to: "{{hostvars[item]['ansible_hostname']}}"
  notify:
  - check_mk inventory
  - check_mk generate
  with_items: groups.icinga
